# 
# Makefile.tmpl for the mod_encrypt module
#
#   Apache v1.3's Configure uses this to create a Makefile 
# 
# $Id: Makefile.tmpl,v 1.6 2000/08/16 01:51:47 robs Exp $

LIB=libencrypt.$(LIBEXT)

OBJS=mod_encrypt.o fcgi_buf.o fcgi_pm.o fcgi_protocol.o	fcgi_config.o fcgi_util.o ./crypt/crypt.o ./crypt/aes256/aes256.o

# Build commands

all:  lib
lib: $(LIB)

libencrypt.a: $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	$(RANLIB) $@
 
libencrypt.so: $(OBJS)
	rm -f $@
	$(LD_SHLIB) $(LDFLAGS_SHLIB) -o $@ $(OBJS)

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $<

clean:
	rm -f $(LIB) $(OBJS)

distclean: clean
	rm -f Makefile


# NOT FOR END USERS!
depend:
	cp Makefile.tmpl Makefile.tmpl.bak \
	    && sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
	    && gcc -MM $(INCLUDES) $(CFLAGS) *.c >> Makefile.new \
	    && sed -e '1,$$s: $(INCDIR)/: $$(INCDIR)/:g' \
	           -e '1,$$s: $(OSDIR)/: $$(OSDIR)/:g' Makefile.new \
		> Makefile.tmpl \
	    && rm Makefile.new

# Dependencies

$(OBJS): fcgi.h           \
         mod_encrypt.h    \
         fcgi_protocol.h  \
         crypt/crypt.h \
         crypt/aes256/aes256.h
     $(INCDIR)/httpd.h               \
     $(INCDIR)/http_config.h         \
     $(INCDIR)/http_request.h        \
     $(INCDIR)/http_core.h           \
     $(INCDIR)/http_protocol.h       \
     $(INCDIR)/http_main.h           \
     $(INCDIR)/http_log.h            \
     $(INCDIR)/util_script.h         \
     $(INCDIR)/http_conf_globals.h   \
     $(INCDIR)/util_md5.h  
